### PR TITLE
German version of JKMV2.act and VoicePackV17.act

### PR DESCRIPTION
**Pull request by RamonaTigier**
Translated version of JKMV2.act 
Language: German ( de_de )

### CODE REVIEW

**Comment by Eahlstan** [comment]
Hiho.

Lines 34 to 41 aren't translated
Line 54 shouldn't be "Voraus"
Line 77 has a spelling error
Line 95 should be "Schnellkommunikation" or something like that?

**Comment by RamonaTigier** [comment]
Heya, 

thank you for having a look into it. 


Lines 34 to 41 are remarked, but now translated

Line 54 is the correct naval command: https://de.wikipedia.org/wiki/Maschinentelegraf ("volle Fahrt voraus" or [short]"Voll Voraus")

Line 77 corrected

Changed Line 95/96 to a more propper command

**Comment by Eahlstan** [comment]
> Heya,

> Line 54 is the correct naval command: https://de.wikipedia.org/wiki/Maschinentelegraf (volle Fahrt voraus)

Line 54 is the command for backwards, if you look at the machine you posted you see that it's "Zurück", not "Vorwärts" (that's line 62. :)

Also that wiki page itself tells you so:

>meist volle Fahrt voraus, halbe Fahrt, langsame Fahrt, Stop, langsame Fahrt zurück, halbe Fahrt zurück und volle Fahrt zurück

**Comment by RamonaTigier** [comment]
Heya.. 

> 
> Line 54 is the command for backwards, if you look at the machine you posted you see that it's "Zurück", not "Vorwärts" (that's line 62. :)

you're right. :) 
 
> Also that wiki page itself tells you so:
> 
> > meist "volle Fahrt voraus", "halbe Fahrt", "langsame Fahrt", "Stop", "langsame Fahrt zurück", "halbe Fahrt zurück" und "volle Fahrt zurück"

meist is the german word for "mostly" and not part of the command itself. (just to shit clever ;) )

**Comment by Eahlstan** [comment]
I don't want to be pedantic, but if you use "achtern" as a synonym for "zurück" in the following lines I would use either "achtern" on line 54 too, or "zurück" on the following lines to keep it consistent.

Außerdem ist Deutsch meine Muttersprache, ich weiß daher was "meist" bedeutet, ich habe einfach nur den kompletten Satz aus der Klammer des Artikels zitiert :-)

**Comment by RamonaTigier** [comment]
Dann sag das doch.. :P 

Und ja, ich gebe dir recht und finde es nicht pedantisch. :)

Corrected. :)

**Comment by Eahlstan** [comment]
Well I'm keeping it english so that @robbyxp1 knows what's going on, he told me to review this thing because he didn't know if there were some nasty things hiding in here (there are bad people on the net).

**Comment by RamonaTigier** [comment]
Feeling fine with english and that's a good idea to keep the files checked before pulling. 
(next Project is VoicePackV17.act but there is only 80% roughly done).

**Comment by Eahlstan** [comment]
Are you using the german translation of EDD? If you do and see any errors there please tell me. I did that translation but I'm not using it myself, so there might be errors hiding.

**Comment by RamonaTigier** [comment]
> Are you using the german translation of EDD? If you do and see any errors there please tell me. I did that translation but I'm not using it myself, so there might be errors hiding.

Yes using the german version and I'll having a look into it and will come back to you. 
For the present uses (think I'm using it for 2 years!?) I havn't mentioned errors, but my german isn't that perfect. ^^

**Comment by RamonaTigier** [comment]
@Eahlstan 
When displaying: 
{"timestamp":"2021-09-17T17:07:25Z","event":"LoadGame","FID":"F412506","Commander":"Ramona Tigier","Horizons":true,"Odyssey":true,"Ship":"Python","ShipID":3,"ShipName":"TRAHAULCHE-3","ShipIdent":"THC-3","FuelLevel":32.0,"FuelCapacity":32.0,"GameMode":"Solo","Credits":238436852,"Loan":0,"language":"German/DE","gameversion":"4.0.0.701","build":"r273365/r0 "}

In History-Tab Name of the Ship is displayed as:
"NameTRAHAULCHE-3"
instead of
"Name: TRAHAULCHE-3"

Sure this is no grammar or spelling, but you asked for hiding errors. :) 

(Is there another thread where I can post this? Thinking here it is the wrong one ;) )

image

**Comment by Eahlstan** [comment]
Found and fixed. Thank you.

**Comment by RamonaTigier** [comment]
Welcome.. :) 

image

Missions-Tab
"Mission" instead of "1Mission"!? Maybe?

**Comment by Eahlstan** [comment]
Damned be those leading spaces :D

Are you on Discord? Might be better than spamming here.

**Comment by RamonaTigier** [comment]
:) 
Glad to help..

Sure, Discord.. Official EDD Channel??

**Comment by RamonaTigier** [comment]
Initial Version of translated VoicePackV17German.act commited. 

@Eahlstan have fun and I look forward to your verdict.. :P

**Comment by Eahlstan** [comment]
Line 309 "Schelichfahrt"
Frontier translates "fuel scoop" as "Treibstoffsammler" and "fuel as "Treibstoff" (https://d1wv0x2frmpnh.cloudfront.net/elite/website/assets/German-PlayersGuide_v2.20-TheGuardians.pdf page 39) EDDs german translation follows this, so you might want to change your translation (in this logic "scoop" is translated with "sammeln" not "schöpfen").
"Wing" is called "Geschwader", applies to all lines.
Line 314 isn't consistent as you're using two different translations for "mass lock". And "supercruise" isn't "Überschallflug", Frontier (and EDD) don't translate this at all (this applies to all lines where you used "Überschall").
Line 341 "Settlement" is "Siedlung" not "Kolonisation" (and even if it was it would be "Kolonie")
Lines 361 and 362: I'm unsure if "collect" and "deliver" should be translated, you might want to ask Robby about that (EventClass_UpdateEnum,\"Collect\").
"Capital ship" is "Großkampfschiff", not "Großschiff".
Line 369 It's "verhängt", not "verhangen". ( https://www.dwds.de/wb/verh%C3%A4ngen not https://www.dwds.de/wb/verhangen )
Line 372: I wouldn't put "System" after the system name
Line 373: "Systgem", remark from above applies
Line 374: See above
On all lines: "Community goal" is translated as "Community-Ziel" both in game and in EDD.
Line 380: I think ""illkommen  auf unserem Schiff Kommandant %(EventClass_Crew)" would sound better
Line 384: "Kommander"
Line 388: "Donnerkeil"? oO Never heard that as a synonym for "Wow". Don't you think "Wahnsinn" would be more fitting?
Lines 392, 393: "Loadout" is translated as "Konfiguration" if it's regarding suits.
Line 399: It's "Sternenhafen"
Line 403 could result in "Der Wert ist XY Kredits wert"
Line 412: If you're playing the german version could you check if "landing pad" is translated as "Landeplatz"? It's "Landeplattform" in EDD so far and I want it to be consistent. (Also you're translating it as "Platz" at first and "Plattform" later on)
Lines 431, 433: I'd replace "Docking" with "Landung" ("Landungs-Anfrage", "Landungs-Ansuchen", "Landung anfordern", ...)
Fighter isn't translated in game and in EDD, so it would be consistent to not call them "Kampfschiff".
Line 445: "Type" should be "Typ", but it's translated as "Art" all over EDD.
Lines 451, 452: I'm not familiar with the syntax, but either "atmosphere" shouldn't be translated or "volcanism" should be.
Line 460: "Modul" not "Module"
Line 465: "Fragt an" not "Anfragen"
Lines 474, 475: On one line you're saying "Gestirn" on the other "Körper" both refer to the same thing. Personally I wouldn't use "Gestirn" as this isn't a thing that normally includes small dark objects.
Lines 479, 480, 482, 483: Not translated
Line 524: If you're submitting to an interdiction you're not submitting anything in a the sense of "einreichen". I see that I translated that word as "übermittelt" as I didn't realize where it's used, so if you come up with a more fitting word I'll change my wrong meaning too.
Line 529: It should say something like "'Gesteigert ums X-fache" you're saying "Gesteigert von X Mal"
Line 537: "Drohne"
Lines 542, 543: Loadout thing again
Line 546: I don't think "ausrangieren" is a word that should be used if you're not talking about machines.
Line 580: In all other lines you're using "gescannt".
Line 617: Loadout...
Line 645: "Sonnenmassen" not "Sternmassen" (yeah I know it's that in the original too)
Line 646: "absolute magnitude" shouldn't be translated as " Absolute Größe". See https://de.wikipedia.org/wiki/Scheinbare_Helligkeit
Line 650: "zu" should be "bis"
Line 687: Isn't that contact translated in game?
Line 711: "Rasterschub" sounds funny, but I doubt anyone will know what this is as the FSD is still FSA in german.
Line 718: You should reword that line. Nenne nenne
Line 899: Why take the plural of one and the singular of the other?

**Comment by RamonaTigier** [comment]
That was quick. :)
Many thanks.
Will check issues/errors and correct.

**Comment by RamonaTigier** [comment]
@Eahlstan new version arrived :) :P

**Comment by RamonaTigier** [comment]
@robbyxp1 VoicePackV17 is ready for multilanguage!? Line 963 !? VoicePack next version might be split into Main-code and something similar to PO-files??
I have no idea if ActionScript could handle it.

Link to description: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

Just an idea...

**Comment by Eahlstan** [comment]
>"Gemeinschaftsziel Bringe Eis, aus dem Djapan System, belohnte dich mit 600 Millionen Kredits"
>sure:
>"Gemeinschaftsziel Bringe Eis, aus dem System Djapan, belohnte dich mit 600 Millionen Kredits"
>fits as well

I just think that even though it sound good on systems with a name, "...aus dem Blia Chria BA-A e2 System" sounds worse than "..aus dem System Blia Chria BA-A e2", but that's a matter of opinion not grammar.

Stellar mass is a term used to tell that you're referring to the mass of a star, but it's value is enumerated in multiples of the mass of the sun.
So if you're saying "star XY has 3.6 stellar masses" it doesn't make any sense.

Linked the wrong wiki. It's Absolute Helligkeit.
 https://de.wikipedia.org/wiki/Absolute_Helligkeit
 https://en.wikipedia.org/wiki/Absolute_magnitude

**Comment by RamonaTigier** [comment]
> > "Gemeinschaftsziel Bringe Eis, aus dem Djapan System, belohnte dich mit 600 Millionen Kredits"
> > sure:
> > "Gemeinschaftsziel Bringe Eis, aus dem System Djapan, belohnte dich mit 600 Millionen Kredits"
> > fits as well
> 
> I just think that even though it sound good on systems with a name, "...aus dem Blia Chria BA-A e2 System" sounds worse than "..aus dem System Blia Chria BA-A e2", but that's a matter of opinion not grammar.

you're right. 

> Stellar mass is a term used to tell that you're referring to the mass of a star, but it's value is enumerated in multiples of the mass of the sun.
> So if you're saying "star XY has 3.6 stellar masses" it doesn't make any sense.
> 
> Linked the wrong wiki. It's Absolute Helligkeit.
> https://de.wikipedia.org/wiki/Absolute_Helligkeit
> https://en.wikipedia.org/wiki/Absolute_magnitude

corrected.

**Comment by robbyxp1** [comment]
Thank you.

**Pull request merged**
