### PR TITLE
Add reasons for denied dockings

### PR DESCRIPTION
**Pull request by Eahlstan**
Tigier brought this up, I think that might be a good idea.

### CODE REVIEW

**Comment by Eahlstan** [comment]
The missing { } caused the following lines to not work 50% of the time.

**Comment by robbyxp1** [comment]
think it needs a bit more work, it will say "Busy port Commander" or "Appears Busy", then say the real reason.

**Comment by Eahlstan** [comment]
Is this going in the right direction?

**Comment by robbyxp1** [comment]
looks better, i'll test it out, and we need to increase the voice pack version number.

**Comment by Eahlstan** [comment]
The SAASignalsFound event was completely missing. There sure is a way to let it say "biological" or "geological", but I don't know what eventclass to use.

(Seriously I mentioned this on the Discord a while ago: please update the eventclass text file, the current one is from before Odyssey. Or tell me how to do it, I compiled the EDTools thinking I'd find it there but either I'm blind or it's not there.)

**Comment by robbyxp1** [comment]
Done in 18

**Pull request closed without merging**
